[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.62.2"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://uswds-hugo-theme.netlify.com/"
